### ISSUE TITLE
Found typo: bolean

### ISSUE THREAD

**Issue by ftnext** [gaborbernat/bernat-tech#1]
Thank you for your great work: https://bernat.tech/posts/the-state-of-type-hints-in-python/

I found a typo
https://github.com/gaborbernat/bernat-tech/blob/01807752c4f08f8ea7f1b6c6be0e2b419bfc3fd9/content/posts/type-hints/index.md#L478

It seems boolean(1) or bool(2)

(1): https://docs.python.org/3/library/stdtypes.html#boolean-values
(2): https://docs.python.org/3/library/functions.html#bool

**Comment by gaborbernat** [comment]
Thanks fixed via https://github.com/gaborbernat/bernat-tech/commit/981ec094faac6c80f1cd2a93c2ba02565e677cdf
